/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tcc.lexer;


import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import tcc.lexer.exceptions.MinipascalSemanticException;
import tcc.lexer.service.MiniCompiler;

public class CompilerRunner {

    private static final Logger log = LogManager.getLogger(CompilerRunner.class);

    private static final String INPUT_FILE_PATH = "src/main/java/tcc/lexer/inputs/code.mp";

    public static void main(String[] args) {
        try {
            log.info("Starting Lexer");

            MiniCompiler.lexicalAnalysis(INPUT_FILE_PATH);

            MiniCompiler.syntaxAnalysis(INPUT_FILE_PATH);

            log.info("Program compiled successful!");

        } catch (MinipascalSemanticException ex) {
            log.error("Semantic error found: " + ex.getMessage());
        } catch (Exception e) {
            log.error("Something went wrong: " + e.getMessage());
        }
    }
}
